name = input("What is your name, viewer? ")
print("Welcome to Python,", name, "!")
age = input("How old are you?")
print("Oh I see,", name, "You are" , age, "years old")
input('Right?')
input( "Bye! Press any Alphabet or Number to close.")
